import { WEBSITE_COLOR_KEYS } from "../../../components/Theme/theme-presets";

/**
 * Generates the complete website theme CSS based on form settings.
 * Outputs standard CSS variables for both light and dark modes.
 *
 * Selector strategy:
 * - Light mode: :root (applies globally as baseline)
 * - Dark mode: html.dark (next-themes adds class="dark" to <html>)
 *
 * This matches globals.css which uses @custom-variant dark (&:is(.dark *))
 * and ThemeProvider attribute="class".
 *
 * Font wiring:
 * - Sets --theme-heading-font and --theme-body-font from Payload settings.
 * - Also overrides --font-sans and --font-serif so Tailwind font-sans/font-serif
 *   utility classes reflect the dynamically chosen fonts (not just the static next/font values).
 */
export const generateThemeCSS = (settings: any): string => {
  if (!settings) return "";

  const {
    mode = "light",
    radius = 0.5,
    headingFont = "Playfair Display",
    bodyFont = "Public Sans",
  } = settings;

  // Build font stacks
  const headingFontStack = `'${headingFont}', Georgia, 'Times New Roman', serif`;
  const bodyFontStack = `'${bodyFont}', system-ui, -apple-system, sans-serif`;

  // 1. Base variables — radius + fonts
  // We also override --font-sans and --font-serif here so that Tailwind's
  // font-sans / font-serif utility classes (used in globals.css @layer base)
  // automatically pick up the CMS-chosen fonts at runtime.
  let css = `/* ==========================================
   Chambers Unified Theme - Website Stylesheet
   Auto-generated by Payload CMS ThemeSettings hook.
   DO NOT EDIT MANUALLY.
   ========================================== */

:root {
  --radius: ${radius}rem;
  --theme-heading-font: ${headingFontStack};
  --theme-body-font: ${bodyFontStack};
  /* Override Tailwind font stacks so font-sans/font-serif classes use the CMS fonts */
  --font-sans: ${bodyFontStack};
  --font-serif: ${headingFontStack};
}
`;

  // Helper: get dark override value (falls back to light value if not set)
  const getDarkValue = (key: string) => {
    const darkKey = `${key}Dark`;
    return settings[darkKey] || settings[key] || "";
  };

  // 2. Generate Light Mode variables (applied to :root)
  // Always output light vars unless mode is forced-dark only.
  if (mode === "light" || mode === "system") {
    let lightVars = "\n:root {\n";
    WEBSITE_COLOR_KEYS.forEach((key) => {
      const val = settings[key];
      if (val) {
        lightVars += `  --${camelToKebab(key)}: ${val};\n`;
      }
    });
    lightVars += "}\n";
    css += lightVars;
  }

  // 3. If mode is forced "dark", we still need to set light-mode :root vars
  // so the page has valid base variables, then override below.
  if (mode === "dark") {
    let darkRootBase = "\n:root {\n  /* Forced dark mode — root base (light values as fallback) */\n";
    WEBSITE_COLOR_KEYS.forEach((key) => {
      // Use the dark value (falls back to light if no dark override set)
      const val = getDarkValue(key);
      if (val) {
        darkRootBase += `  --${camelToKebab(key)}: ${val};\n`;
      }
    });
    darkRootBase += "}\n";
    css += darkRootBase;
  }

  // 4. Generate Dark Mode variables (applied when html has class="dark" from next-themes)
  if (mode === "dark" || mode === "system") {
    let darkVars = "\nhtml.dark {\n";
    WEBSITE_COLOR_KEYS.forEach((key) => {
      const val = getDarkValue(key);
      if (val) {
        darkVars += `  --${camelToKebab(key)}: ${val};\n`;
      }
    });
    darkVars += "}\n";
    css += darkVars;
  }

  // 5. Append Custom CSS overrides from the CMS CSS Overrides tab
  if (settings.cssOverrides) {
    let customCss = settings.cssOverrides;

    // Sanitize: remove at-rules that are invalid inside an inline <style> tag
    // (@import must be external, @theme/@layer are Tailwind build-time directives)
    customCss = customCss.replace(/@import\s+[^;]+;/g, "/* @import removed — not valid in inline styles */");
    customCss = customCss.replace(/@(theme|layer|custom-variant|tailwind)\s*(?:inline)?\s*\{[\s\S]*?\}/g, "");

    // Normalize :root -> :root (no longer using html:root)
    customCss = customCss.replace(/html:root/g, ":root");
    // Keep .dark -> html.dark for next-themes compatibility
    customCss = customCss.replace(/(?<!html)\.dark(?=\s|{|,)/g, "html.dark");

    // Only append if there's meaningful content left
    const trimmedCustomCss = customCss.trim();
    if (trimmedCustomCss && trimmedCustomCss.length > 10) {
      css += `\n/* === Custom CSS Overrides from Payload CMS === */\n${trimmedCustomCss}\n`;
    }
  }

  return css;
};

/**
 * Utility to convert camelCase keys (like primaryForeground) to kebab-case (like primary-foreground)
 */
function camelToKebab(str: string): string {
  return str.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, "$1-$2").toLowerCase();
}

