import { WEBSITE_COLOR_KEYS } from "../../../components/Theme/theme-presets";

/**
 * Generates the complete website theme CSS based on form settings.
 * Outputs standard CSS variables for both light and dark modes.
 *
 * Selector strategy:
 * - Light mode: :root  (applies globally as baseline)
 * - Dark mode: html.dark (next-themes adds class="dark" to <html>)
 *
 * This matches globals.css which uses @custom-variant dark (&:is(.dark *))
 * and ThemeProvider attribute="class".
 */
export const generateThemeCSS = (settings: any): string => {
  if (!settings) return "";

  const {
    mode = "light",
    radius = 0.5,
    headingFont = "Playfair Display",
    bodyFont = "Public Sans",
  } = settings;

  // 1. Compile radius base — fonts are loaded via next/font in layout, we only set fallbacks
  let css = `/* ==========================================
   Chambers Unified Theme - Website Stylesheet
   Auto-generated by Payload CMS ThemeSettings hook.
   DO NOT EDIT MANUALLY.
   ========================================== */

:root {
  --radius: ${radius}rem;
  --theme-heading-font: '${headingFont}', Georgia, 'Times New Roman', serif;
  --theme-body-font: '${bodyFont}', system-ui, -apple-system, sans-serif;
}
`;

  // Helper: get dark override value (falls back to light value if not set)
  const getDarkValue = (key: string) => {
    const darkKey = `${key}Dark`;
    return settings[darkKey] || settings[key] || "";
  };

  // 2. Generate Light Mode variables (applied to :root)
  if (mode === "light" || mode === "system") {
    let lightVars = "\n:root {\n";
    WEBSITE_COLOR_KEYS.forEach((key) => {
      const val = settings[key];
      if (val) {
        lightVars += `  --${camelToKebab(key)}: ${val};\n`;
      }
    });
    lightVars += "}\n";
    css += lightVars;
  }

  // 3. Generate Dark Mode variables (applied when html has class="dark" from next-themes)
  if (mode === "dark" || mode === "system") {
    let darkVars = "\nhtml.dark {\n";
    WEBSITE_COLOR_KEYS.forEach((key) => {
      const val = getDarkValue(key);
      if (val) {
        darkVars += `  --${camelToKebab(key)}: ${val};\n`;
      }
    });
    darkVars += "}\n";
    css += darkVars;
  }

  // 4. If mode is "dark" (forced dark), also override :root so base styles are dark
  if (mode === "dark") {
    let forceDarkRoot = "\n:root {\n  /* Forced dark mode — override root defaults */\n";
    WEBSITE_COLOR_KEYS.forEach((key) => {
      const val = getDarkValue(key);
      if (val) {
        forceDarkRoot += `  --${camelToKebab(key)}: ${val};\n`;
      }
    });
    forceDarkRoot += "}\n";
    css += forceDarkRoot;
  }

  return css;
};

/**
 * Utility to convert camelCase keys (like primaryForeground) to kebab-case (like primary-foreground)
 */
function camelToKebab(str: string): string {
  return str.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, "$1-$2").toLowerCase();
}
