export interface ColorPreset {
  name: string;
  label: string;
  websiteColors: Record<string, string>;
  adminColors: Record<string, string>;
  websiteRadius: number;
  adminRadius: number;
}

export const THEME_PRESETS: Record<string, ColorPreset> = {
  chambersClassic: {
    name: "chambersClassic",
    label: "Chambers Classic (Deep Navy & Subtle Gold)",
    websiteColors: {
      background: "#ffffff",
      foreground: "#1e293b",
      primary: "#0f1729",
      primaryForeground: "#ffffff",
      secondary: "#f8fafc",
      secondaryForeground: "#0f1729",
      card: "#ffffff",
      cardForeground: "#1e293b",
      popover: "#ffffff",
      popoverForeground: "#1e293b",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      accent: "#d4af37",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#d4af37",
    },
    adminColors: {
      adminBg: "#ffffff",
      adminFg: "#0f1729",
      adminPrimary: "#0f1729",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f8fafc",
      adminSecondaryFg: "#0f1729",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#0f1729",
      adminAccent: "#d4af37",
      adminAccentFg: "#ffffff",
      adminBorder: "#e2e8f0",
      adminMuted: "#64748b",
    },
    websiteRadius: 0.5,
    adminRadius: 0.375,
  },
  slateMinimalist: {
    name: "slateMinimalist",
    label: "Slate Minimalist (Stark Charcoal)",
    websiteColors: {
      background: "#ffffff",
      foreground: "#111827",
      primary: "#1f2937",
      primaryForeground: "#ffffff",
      secondary: "#f3f4f6",
      secondaryForeground: "#111827",
      card: "#ffffff",
      cardForeground: "#111827",
      popover: "#ffffff",
      popoverForeground: "#111827",
      muted: "#f3f4f6",
      mutedForeground: "#4b5563",
      accent: "#374151",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#1f2937",
    },
    adminColors: {
      adminBg: "#ffffff",
      adminFg: "#111827",
      adminPrimary: "#1f2937",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f3f4f6",
      adminSecondaryFg: "#111827",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#111827",
      adminAccent: "#374151",
      adminAccentFg: "#ffffff",
      adminBorder: "#e5e7eb",
      adminMuted: "#4b5563",
    },
    websiteRadius: 0.25,
    adminRadius: 0.25,
  },
  emeraldEditorial: {
    name: "emeraldEditorial",
    label: "Emerald Editorial (Emerald Green & Gold Accents)",
    websiteColors: {
      background: "#ffffff",
      foreground: "#111827",
      primary: "#064e3b",
      primaryForeground: "#ffffff",
      secondary: "#f0fdf4",
      secondaryForeground: "#064e3b",
      card: "#ffffff",
      cardForeground: "#111827",
      popover: "#ffffff",
      popoverForeground: "#111827",
      muted: "#f3f4f6",
      mutedForeground: "#4b5563",
      accent: "#d4af37",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#064e3b",
    },
    adminColors: {
      adminBg: "#ffffff",
      adminFg: "#111827",
      adminPrimary: "#064e3b",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f0fdf4",
      adminSecondaryFg: "#064e3b",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#111827",
      adminAccent: "#d4af37",
      adminAccentFg: "#ffffff",
      adminBorder: "#e5e7eb",
      adminMuted: "#4b5563",
    },
    websiteRadius: 0.375,
    adminRadius: 0.25,
  },
  amberExecutive: {
    name: "amberExecutive",
    label: "Amber Executive (Charcoal & Warm Amber)",
    websiteColors: {
      background: "#fdfbf7",
      foreground: "#111827",
      primary: "#1f2937",
      primaryForeground: "#ffffff",
      secondary: "#f5f5f4",
      secondaryForeground: "#1c1917",
      card: "#ffffff",
      cardForeground: "#111827",
      popover: "#ffffff",
      popoverForeground: "#111827",
      muted: "#fafaf9",
      mutedForeground: "#78716c",
      accent: "#d97706",
      accentForeground: "#ffffff",
      destructive: "#b91c1c",
      destructiveForeground: "#ffffff",
      border: "#e7e5e4",
      input: "#e7e5e4",
      ring: "#d97706",
    },
    adminColors: {
      adminBg: "#fdfbf7",
      adminFg: "#1c1917",
      adminPrimary: "#1f2937",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f5f5f4",
      adminSecondaryFg: "#1c1917",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#1c1917",
      adminAccent: "#d97706",
      adminAccentFg: "#ffffff",
      adminBorder: "#e7e5e4",
      adminMuted: "#78716c",
    },
    websiteRadius: 0.5,
    adminRadius: 0.375,
  },
  crimsonCourt: {
    name: "crimsonCourt",
    label: "Crimson Court (Burgundy & Brass)",
    websiteColors: {
      background: "#ffffff",
      foreground: "#111827",
      primary: "#7f1d1d",
      primaryForeground: "#ffffff",
      secondary: "#fef2f2",
      secondaryForeground: "#7f1d1d",
      card: "#ffffff",
      cardForeground: "#111827",
      popover: "#ffffff",
      popoverForeground: "#111827",
      muted: "#f9fafb",
      mutedForeground: "#6b7280",
      accent: "#c5a880",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      border: "#f3f4f6",
      input: "#f3f4f6",
      ring: "#7f1d1d",
    },
    adminColors: {
      adminBg: "#ffffff",
      adminFg: "#111827",
      adminPrimary: "#7f1d1d",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#fef2f2",
      adminSecondaryFg: "#7f1d1d",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#111827",
      adminAccent: "#c5a880",
      adminAccentFg: "#ffffff",
      adminBorder: "#e5e7eb",
      adminMuted: "#6b7280",
    },
    websiteRadius: 0.25,
    adminRadius: 0.25,
  },
  royalBar: {
    name: "royalBar",
    label: "Royal Bar (Royal Blue & Gold)",
    websiteColors: {
      background: "#ffffff",
      foreground: "#111827",
      primary: "#1e3a8a",
      primaryForeground: "#ffffff",
      secondary: "#eff6ff",
      secondaryForeground: "#1e3a8a",
      card: "#ffffff",
      cardForeground: "#111827",
      popover: "#ffffff",
      popoverForeground: "#111827",
      muted: "#f3f4f6",
      mutedForeground: "#4b5563",
      accent: "#d4af37",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#1e3a8a",
    },
    adminColors: {
      adminBg: "#ffffff",
      adminFg: "#111827",
      adminPrimary: "#1e3a8a",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#eff6ff",
      adminSecondaryFg: "#1e3a8a",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#111827",
      adminAccent: "#d4af37",
      adminAccentFg: "#ffffff",
      adminBorder: "#e5e7eb",
      adminMuted: "#4b5563",
    },
    websiteRadius: 0.5,
    adminRadius: 0.375,
  },
  midnightExecutive: {
    name: "midnightExecutive",
    label: "Midnight Executive (Midnight Blue & Silver)",
    websiteColors: {
      background: "#0b0f19",
      foreground: "#f1f5f9",
      primary: "#1e293b",
      primaryForeground: "#ffffff",
      secondary: "#0f172a",
      secondaryForeground: "#f1f5f9",
      card: "#0f172a",
      cardForeground: "#f1f5f9",
      popover: "#0f172a",
      popoverForeground: "#f1f5f9",
      muted: "#1e293b",
      mutedForeground: "#94a3b8",
      accent: "#94a3b8",
      accentForeground: "#0b0f19",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#334155",
      input: "#334155",
      ring: "#94a3b8",
    },
    adminColors: {
      adminBg: "#0b0f19",
      adminFg: "#f1f5f9",
      adminPrimary: "#1e293b",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#0f172a",
      adminSecondaryFg: "#f1f5f9",
      adminSurface: "#0f172a",
      adminSurfaceFg: "#f1f5f9",
      adminAccent: "#94a3b8",
      adminAccentFg: "#0b0f19",
      adminBorder: "#334155",
      adminMuted: "#94a3b8",
    },
    websiteRadius: 0.375,
    adminRadius: 0.25,
  },
  bronzeBrief: {
    name: "bronzeBrief",
    label: "Bronze Brief (Earthy Bronze & Brass)",
    websiteColors: {
      background: "#fdfcfb",
      foreground: "#2d2219",
      primary: "#4a3728",
      primaryForeground: "#ffffff",
      secondary: "#f7f4f0",
      secondaryForeground: "#4a3728",
      card: "#ffffff",
      cardForeground: "#2d2219",
      popover: "#ffffff",
      popoverForeground: "#2d2219",
      muted: "#f5f0eb",
      mutedForeground: "#806b5c",
      accent: "#c5a880",
      accentForeground: "#ffffff",
      destructive: "#991b1b",
      destructiveForeground: "#ffffff",
      border: "#e8dfd5",
      input: "#e8dfd5",
      ring: "#4a3728",
    },
    adminColors: {
      adminBg: "#fdfcfb",
      adminFg: "#2d2219",
      adminPrimary: "#4a3728",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f7f4f0",
      adminSecondaryFg: "#4a3728",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#2d2219",
      adminAccent: "#c5a880",
      adminAccentFg: "#ffffff",
      adminBorder: "#e8dfd5",
      adminMuted: "#806b5c",
    },
    websiteRadius: 0.5,
    adminRadius: 0.375,
  },
  forestFiducia: {
    name: "forestFiducia",
    label: "Forest Fiducia (Forest Green & Warm Slate)",
    websiteColors: {
      background: "#fcfbf7",
      foreground: "#1b4332",
      primary: "#1b4332",
      primaryForeground: "#ffffff",
      secondary: "#f4f2ea",
      secondaryForeground: "#1b4332",
      card: "#ffffff",
      cardForeground: "#1b4332",
      popover: "#ffffff",
      popoverForeground: "#1b4332",
      muted: "#e9e6da",
      mutedForeground: "#64748b",
      accent: "#475569",
      accentForeground: "#ffffff",
      destructive: "#991b1b",
      destructiveForeground: "#ffffff",
      border: "#e1ded2",
      input: "#e1ded2",
      ring: "#1b4332",
    },
    adminColors: {
      adminBg: "#fcfbf7",
      adminFg: "#1b4332",
      adminPrimary: "#1b4332",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f4f2ea",
      adminSecondaryFg: "#1b4332",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#1b4332",
      adminAccent: "#475569",
      adminAccentFg: "#ffffff",
      adminBorder: "#e1ded2",
      adminMuted: "#64748b",
    },
    websiteRadius: 0.75,
    adminRadius: 0.5,
  },
  sapphireSolace: {
    name: "sapphireSolace",
    label: "Sapphire Solace (Sapphire Blue & Silver)",
    websiteColors: {
      background: "#ffffff",
      foreground: "#0f172a",
      primary: "#0f172a",
      primaryForeground: "#ffffff",
      secondary: "#f1f5f9",
      secondaryForeground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      muted: "#f8fafc",
      mutedForeground: "#64748b",
      accent: "#64748b",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#0f172a",
    },
    adminColors: {
      adminBg: "#ffffff",
      adminFg: "#0f172a",
      adminPrimary: "#0f172a",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f1f5f9",
      adminSecondaryFg: "#0f172a",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#0f172a",
      adminAccent: "#64748b",
      adminAccentFg: "#ffffff",
      adminBorder: "#e2e8f0",
      adminMuted: "#64748b",
    },
    websiteRadius: 0.375,
    adminRadius: 0.25,
  },
  platinumPrestige: {
    name: "platinumPrestige",
    label: "Platinum Prestige (Platinum & Charcoal)",
    websiteColors: {
      background: "#f8fafc",
      foreground: "#0f172a",
      primary: "#334155",
      primaryForeground: "#ffffff",
      secondary: "#e2e8f0",
      secondaryForeground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      accent: "#0f172a",
      accentForeground: "#ffffff",
      destructive: "#e11d48",
      destructiveForeground: "#ffffff",
      border: "#cbd5e1",
      input: "#cbd5e1",
      ring: "#334155",
    },
    adminColors: {
      adminBg: "#f8fafc",
      adminFg: "#0f172a",
      adminPrimary: "#334155",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#e2e8f0",
      adminSecondaryFg: "#0f172a",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#0f172a",
      adminAccent: "#0f172a",
      adminAccentFg: "#ffffff",
      adminBorder: "#cbd5e1",
      adminMuted: "#64748b",
    },
    websiteRadius: 0.25,
    adminRadius: 0.125,
  },
  terracottaTribunal: {
    name: "terracottaTribunal",
    label: "Terracotta Tribunal (Terracotta & Charcoal)",
    websiteColors: {
      background: "#fafaf9",
      foreground: "#1c1917",
      primary: "#7c2d12",
      primaryForeground: "#ffffff",
      secondary: "#f5f5f4",
      secondaryForeground: "#7c2d12",
      card: "#ffffff",
      cardForeground: "#1c1917",
      popover: "#ffffff",
      popoverForeground: "#1c1917",
      muted: "#f5f5f4",
      mutedForeground: "#78716c",
      accent: "#292524",
      accentForeground: "#ffffff",
      destructive: "#b91c1c",
      destructiveForeground: "#ffffff",
      border: "#e7e5e4",
      input: "#e7e5e4",
      ring: "#7c2d12",
    },
    adminColors: {
      adminBg: "#fafaf9",
      adminFg: "#1c1917",
      adminPrimary: "#7c2d12",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f5f5f4",
      adminSecondaryFg: "#7c2d12",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#1c1917",
      adminAccent: "#292524",
      adminAccentFg: "#ffffff",
      adminBorder: "#e7e5e4",
      adminMuted: "#78716c",
    },
    websiteRadius: 0.5,
    adminRadius: 0.375,
  },
  oxfordObiter: {
    name: "oxfordObiter",
    label: "Oxford Obiter (Oxford Blue & Premium Gold)",
    websiteColors: {
      background: "#fdfbf7",
      foreground: "#0f172a",
      primary: "#0f172a",
      primaryForeground: "#ffffff",
      secondary: "#f5f2eb",
      secondaryForeground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      muted: "#faf6ee",
      mutedForeground: "#5c6370",
      accent: "#d4af37",
      accentForeground: "#0f172a",
      destructive: "#991b1b",
      destructiveForeground: "#ffffff",
      border: "#e8dfd0",
      input: "#e8dfd0",
      ring: "#d4af37",
    },
    adminColors: {
      adminBg: "#fdfbf7",
      adminFg: "#0f172a",
      adminPrimary: "#0f172a",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f5f2eb",
      adminSecondaryFg: "#0f172a",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#0f172a",
      adminAccent: "#d4af37",
      adminAccentFg: "#0f172a",
      adminBorder: "#e8dfd0",
      adminMuted: "#5c6370",
    },
    websiteRadius: 0.375,
    adminRadius: 0.25,
  },
  teakTrustee: {
    name: "teakTrustee",
    label: "Teak Trustee (Teak Wood & Bronze)",
    websiteColors: {
      background: "#fdfaf2",
      foreground: "#451a03",
      primary: "#451a03",
      primaryForeground: "#ffffff",
      secondary: "#f5ede0",
      secondaryForeground: "#451a03",
      card: "#ffffff",
      cardForeground: "#451a03",
      popover: "#ffffff",
      popoverForeground: "#451a03",
      muted: "#fdfaf2",
      mutedForeground: "#78716c",
      accent: "#c5a880",
      accentForeground: "#ffffff",
      destructive: "#991b1b",
      destructiveForeground: "#ffffff",
      border: "#e7dbcb",
      input: "#e7dbcb",
      ring: "#451a03",
    },
    adminColors: {
      adminBg: "#fdfaf2",
      adminFg: "#451a03",
      adminPrimary: "#451a03",
      adminPrimaryFg: "#ffffff",
      adminSecondary: "#f5ede0",
      adminSecondaryFg: "#451a03",
      adminSurface: "#ffffff",
      adminSurfaceFg: "#451a03",
      adminAccent: "#c5a880",
      adminAccentFg: "#ffffff",
      adminBorder: "#e7dbcb",
      adminMuted: "#78716c",
    },
    websiteRadius: 0.5,
    adminRadius: 0.375,
  }
};

export const WEBSITE_COLOR_KEYS = [
  "background", "foreground", "primary", "primaryForeground",
  "secondary", "secondaryForeground", "card", "cardForeground",
  "popover", "popoverForeground", "muted", "mutedForeground",
  "accent", "accentForeground", "destructive", "destructiveForeground",
  "border", "input", "ring"
];

export const ADMIN_COLOR_KEYS = [
  "adminBg", "adminFg", "adminPrimary", "adminPrimaryFg",
  "adminSecondary", "adminSecondaryFg", "adminSurface",
  "adminSurfaceFg", "adminAccent", "adminAccentFg", "adminBorder",
  "adminMuted"
];
