/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    team: Team;
    users: User;
    media: Media;
    posts: Post;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    ga4: Ga4;
    'theme-settings': ThemeSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    ga4: Ga4Select<false> | Ga4Select<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * The URL-friendly identifier for this page.
   */
  slug: string;
  layout?:
    | (
        | {
            layoutType: 'split' | 'centered' | 'asymmetric';
            heading: string;
            subheading?: string | null;
            media?: (string | null) | Media;
            ctas?:
              | {
                  label: string;
                  link: string;
                  style?: ('primary' | 'secondary' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamicHero';
          }
        | {
            title: string;
            subtitle: string;
            ctaText: string;
            ctaLink: string;
            images?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeHero';
          }
        | {
            title: string;
            subtitle: string;
            areas?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: ('Briefcase' | 'Gavel' | 'Building2' | 'Landmark') | null;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'practiceAreas';
          }
        | {
            awards?:
              | {
                  title: string;
                  year?: string | null;
                  organization?: string | null;
                  description?: string | null;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'awardsMarquee';
          }
        | {
            tag: string;
            title: string;
            subtitle: string;
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutHero';
          }
        | {
            tag: string;
            title: string;
            subtitle?: string | null;
            teamMembers?: (string | Team)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutTeam';
          }
        | {
            tag: string;
            title: string;
            subtitle?: string | null;
            values?:
              | {
                  title: string;
                  description: string;
                  icon?: ('Scale' | 'ShieldCheck' | 'Award' | 'Handshake' | 'Gavel' | 'Building2') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutValues';
          }
        | {
            title: string;
            subtitle?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            secondaryCtaText?: string | null;
            secondaryCtaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutCta';
          }
        | {
            tag: string;
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'practiceAreasHero';
          }
        | {
            title: string;
            subtitle?: string | null;
            areas?:
              | {
                  title: string;
                  description?: string | null;
                  icon?:
                    | (
                        | 'Briefcase'
                        | 'Gavel'
                        | 'Building2'
                        | 'Landmark'
                        | 'Scale'
                        | 'Shield'
                        | 'FileText'
                        | 'Users'
                        | 'Lightbulb'
                        | 'Home'
                        | 'TrendingDown'
                        | 'Map'
                        | 'MessageSquare'
                      )
                    | null;
                  services?:
                    | {
                        name: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'practiceAreasGrid';
          }
        | {
            badge?: string | null;
            title: string;
            subtitle?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            phoneNumber?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'practiceAreasCta';
          }
        | {
            tag: string;
            title: string;
            subtitle?: string | null;
            phone?: string | null;
            email?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactHero';
          }
        | {
            infoItems?:
              | {
                  icon?: ('Phone' | 'Mail' | 'MapPin' | 'Clock') | null;
                  title: string;
                  value: string;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            badge?: string | null;
            title: string;
            subtitle?: string | null;
            features?:
              | {
                  icon?: ('Clock' | 'Users' | 'ShieldCheck') | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            mapUrl: string;
            locationTitle?: string | null;
            locationAddress?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactMap';
          }
        | {
            tag: string;
            title: string;
            subtitle?: string | null;
            featuredPost?: (string | null) | Post;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogHero';
          }
        | {
            title: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogFilters';
          }
        | {
            badge?: string | null;
            title: string;
            subtitle?: string | null;
            buttonText?: string | null;
            disclaimer?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            tag: string;
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'officeHero';
          }
        | {
            title: string;
            subtitle?: string | null;
            offices?:
              | {
                  id: string | null;
                  label: string;
                  name: string;
                  address: string;
                  phone?:
                    | {
                        number: string;
                        id?: string | null;
                      }[]
                    | null;
                  email?: string | null;
                  mapUrl?: string | null;
                  image?: (string | null) | Media;
                  hours?:
                    | {
                        day: string;
                        time: string;
                        id?: string | null;
                      }[]
                    | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'officeSelector';
          }
        | {
            title: string;
            subtitle?: string | null;
            features?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            mapOverlayTitle?: string | null;
            mapOverlayDescription?: string | null;
            mapUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mapSection';
          }
        | {
            badge?: string | null;
            title: string;
            subtitle?: string | null;
            ctaText1?: string | null;
            ctaLink1?: string | null;
            ctaText2?: string | null;
            ctaLink2?: string | null;
            disclaimer?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'officeCta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  name: string;
  slug: string;
  designation: string;
  subtitle?: string | null;
  image?: (string | null) | Media;
  stats?: {
    experience?: string | null;
    cases?: string | null;
    publications?: string | null;
    clients?: string | null;
  };
  bio?:
    | {
        paragraph?: string | null;
        id?: string | null;
      }[]
    | null;
  overview?: {
    expertise?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
    clients?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
    cases?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  experience?:
    | {
        title: string;
        organization: string;
        period?: string | null;
        responsibilities?:
          | {
              item?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        degree: string;
        institution: string;
        period?: string | null;
        specialization?: string | null;
        id?: string | null;
      }[]
    | null;
  awards?:
    | {
        title: string;
        year?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  publications?:
    | {
        title: string;
        publisher?: string | null;
        year?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug?: string | null;
  category: 'General Legal' | 'Criminal Defense' | 'Corporate Law' | 'Family Law';
  author?: string | null;
  readTime?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt?: string | null;
  featuredImage?: (string | null) | Media;
  status?: ('draft' | 'published') | null;
  /**
   * Optional: Redirect to an external URL instead of showing content in a modal.
   */
  externalLink?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        dynamicHero?:
          | T
          | {
              layoutType?: T;
              heading?: T;
              subheading?: T;
              media?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    link?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeHero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              ctaText?: T;
              ctaLink?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        practiceAreas?:
          | T
          | {
              title?: T;
              subtitle?: T;
              areas?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        awardsMarquee?:
          | T
          | {
              awards?:
                | T
                | {
                    title?: T;
                    year?: T;
                    organization?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutHero?:
          | T
          | {
              tag?: T;
              title?: T;
              subtitle?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        aboutTeam?:
          | T
          | {
              tag?: T;
              title?: T;
              subtitle?: T;
              teamMembers?: T;
              id?: T;
              blockName?: T;
            };
        aboutValues?:
          | T
          | {
              tag?: T;
              title?: T;
              subtitle?: T;
              values?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutCta?:
          | T
          | {
              title?: T;
              subtitle?: T;
              ctaText?: T;
              ctaLink?: T;
              secondaryCtaText?: T;
              secondaryCtaLink?: T;
              id?: T;
              blockName?: T;
            };
        practiceAreasHero?:
          | T
          | {
              tag?: T;
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        practiceAreasGrid?:
          | T
          | {
              title?: T;
              subtitle?: T;
              areas?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    services?:
                      | T
                      | {
                          name?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        practiceAreasCta?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              ctaText?: T;
              ctaLink?: T;
              phoneNumber?: T;
              id?: T;
              blockName?: T;
            };
        contactHero?:
          | T
          | {
              tag?: T;
              title?: T;
              subtitle?: T;
              phone?: T;
              email?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              infoItems?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    value?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactMap?:
          | T
          | {
              mapUrl?: T;
              locationTitle?: T;
              locationAddress?: T;
              id?: T;
              blockName?: T;
            };
        blogHero?:
          | T
          | {
              tag?: T;
              title?: T;
              subtitle?: T;
              featuredPost?: T;
              id?: T;
              blockName?: T;
            };
        blogFilters?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              buttonText?: T;
              disclaimer?: T;
              id?: T;
              blockName?: T;
            };
        officeHero?:
          | T
          | {
              tag?: T;
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        officeSelector?:
          | T
          | {
              title?: T;
              subtitle?: T;
              offices?:
                | T
                | {
                    id?: T;
                    label?: T;
                    name?: T;
                    address?: T;
                    phone?:
                      | T
                      | {
                          number?: T;
                          id?: T;
                        };
                    email?: T;
                    mapUrl?: T;
                    image?: T;
                    hours?:
                      | T
                      | {
                          day?: T;
                          time?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        mapSection?:
          | T
          | {
              title?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              mapOverlayTitle?: T;
              mapOverlayDescription?: T;
              mapUrl?: T;
              id?: T;
              blockName?: T;
            };
        officeCta?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              ctaText1?: T;
              ctaLink1?: T;
              ctaText2?: T;
              ctaLink2?: T;
              disclaimer?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  designation?: T;
  subtitle?: T;
  image?: T;
  stats?:
    | T
    | {
        experience?: T;
        cases?: T;
        publications?: T;
        clients?: T;
      };
  bio?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  overview?:
    | T
    | {
        expertise?:
          | T
          | {
              item?: T;
              id?: T;
            };
        clients?:
          | T
          | {
              item?: T;
              id?: T;
            };
        cases?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  experience?:
    | T
    | {
        title?: T;
        organization?: T;
        period?: T;
        responsibilities?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  education?:
    | T
    | {
        degree?: T;
        institution?: T;
        period?: T;
        specialization?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        title?: T;
        year?: T;
        description?: T;
        id?: T;
      };
  publications?:
    | T
    | {
        title?: T;
        publisher?: T;
        year?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  author?: T;
  readTime?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  status?: T;
  externalLink?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  headerStyle?: ('classic' | 'centered' | 'glassmorphic' | 'minimal') | null;
  sticky?: boolean | null;
  showCTA?: boolean | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  logo?: (string | null) | Media;
  navItems?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ga4".
 */
export interface Ga4 {
  id: string;
  measurementId?: string | null;
  propertyId?: string | null;
  clientEmail?: string | null;
  privateKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: string;
  /**
   * Selecting a preset automatically populates colors. Modifying colors will switch it to Custom.
   */
  preset:
    | 'chambersClassic'
    | 'slateMinimalist'
    | 'emeraldEditorial'
    | 'amberExecutive'
    | 'crimsonCourt'
    | 'royalBar'
    | 'midnightExecutive'
    | 'bronzeBrief'
    | 'forestFiducia'
    | 'sapphireSolace'
    | 'platinumPrestige'
    | 'terracottaTribunal'
    | 'oxfordObiter'
    | 'teakTrustee'
    | 'custom';
  /**
   * Controls the active mode of both storefront and admin panel.
   */
  mode: 'system' | 'light' | 'dark';
  /**
   * Controls button, card, and input border radius on website.
   */
  radius: number;
  /**
   * Controls button, modal, and card border radius in admin.
   */
  adminRadius: number;
  /**
   * Google Font name for all headings (h1, h2, h3, etc.).
   */
  headingFont: string;
  /**
   * Google Font name for base reading text and elements.
   */
  bodyFont: string;
  background?: string | null;
  backgroundDark?: string | null;
  foreground?: string | null;
  foregroundDark?: string | null;
  primary?: string | null;
  primaryDark?: string | null;
  primaryForeground?: string | null;
  primaryForegroundDark?: string | null;
  secondary?: string | null;
  secondaryDark?: string | null;
  secondaryForeground?: string | null;
  secondaryForegroundDark?: string | null;
  card?: string | null;
  cardDark?: string | null;
  cardForeground?: string | null;
  cardForegroundDark?: string | null;
  popover?: string | null;
  popoverDark?: string | null;
  popoverForeground?: string | null;
  popoverForegroundDark?: string | null;
  muted?: string | null;
  mutedDark?: string | null;
  mutedForeground?: string | null;
  mutedForegroundDark?: string | null;
  accent?: string | null;
  accentDark?: string | null;
  accentForeground?: string | null;
  accentForegroundDark?: string | null;
  destructive?: string | null;
  destructiveDark?: string | null;
  destructiveForeground?: string | null;
  destructiveForegroundDark?: string | null;
  border?: string | null;
  borderDark?: string | null;
  input?: string | null;
  inputDark?: string | null;
  ring?: string | null;
  ringDark?: string | null;
  /**
   * Advanced styling variables and layout modifications for website pages.
   */
  cssOverrides?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  headerStyle?: T;
  sticky?: T;
  showCTA?: T;
  ctaLabel?: T;
  ctaLink?: T;
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ga4_select".
 */
export interface Ga4Select<T extends boolean = true> {
  measurementId?: T;
  propertyId?: T;
  clientEmail?: T;
  privateKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  preset?: T;
  mode?: T;
  radius?: T;
  adminRadius?: T;
  headingFont?: T;
  bodyFont?: T;
  background?: T;
  backgroundDark?: T;
  foreground?: T;
  foregroundDark?: T;
  primary?: T;
  primaryDark?: T;
  primaryForeground?: T;
  primaryForegroundDark?: T;
  secondary?: T;
  secondaryDark?: T;
  secondaryForeground?: T;
  secondaryForegroundDark?: T;
  card?: T;
  cardDark?: T;
  cardForeground?: T;
  cardForegroundDark?: T;
  popover?: T;
  popoverDark?: T;
  popoverForeground?: T;
  popoverForegroundDark?: T;
  muted?: T;
  mutedDark?: T;
  mutedForeground?: T;
  mutedForegroundDark?: T;
  accent?: T;
  accentDark?: T;
  accentForeground?: T;
  accentForegroundDark?: T;
  destructive?: T;
  destructiveDark?: T;
  destructiveForeground?: T;
  destructiveForegroundDark?: T;
  border?: T;
  borderDark?: T;
  input?: T;
  inputDark?: T;
  ring?: T;
  ringDark?: T;
  cssOverrides?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}